package com.code.data.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.code.data.sqlbean.ChatListBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAT_LIST_BEAN".
*/
public class ChatListBeanDao extends AbstractDao<ChatListBean, Long> {

    public static final String TABLENAME = "CHAT_LIST_BEAN";

    /**
     * Properties of entity ChatListBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MUid = new Property(1, String.class, "mUid", false, "M_UID");
        public final static Property PeerUid = new Property(2, String.class, "peerUid", false, "PEER_UID");
        public final static Property UserType = new Property(3, int.class, "userType", false, "USER_TYPE");
        public final static Property UnreadMsgCount = new Property(4, int.class, "unreadMsgCount", false, "UNREAD_MSG_COUNT");
        public final static Property Account = new Property(5, long.class, "account", false, "ACCOUNT");
        public final static Property OldMessageTime = new Property(6, long.class, "oldMessageTime", false, "OLD_MESSAGE_TIME");
        public final static Property OldMessage = new Property(7, String.class, "oldMessage", false, "OLD_MESSAGE");
        public final static Property Status = new Property(8, int.class, "status", false, "STATUS");
        public final static Property SourceType = new Property(9, int.class, "sourceType", false, "SOURCE_TYPE");
        public final static Property NickName = new Property(10, String.class, "nickName", false, "NICK_NAME");
        public final static Property SendState = new Property(11, int.class, "sendState", false, "SEND_STATE");
        public final static Property UserAvatar = new Property(12, String.class, "userAvatar", false, "USER_AVATAR");
    }


    public ChatListBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ChatListBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAT_LIST_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_UID\" TEXT NOT NULL ," + // 1: mUid
                "\"PEER_UID\" TEXT NOT NULL ," + // 2: peerUid
                "\"USER_TYPE\" INTEGER NOT NULL ," + // 3: userType
                "\"UNREAD_MSG_COUNT\" INTEGER NOT NULL ," + // 4: unreadMsgCount
                "\"ACCOUNT\" INTEGER NOT NULL ," + // 5: account
                "\"OLD_MESSAGE_TIME\" INTEGER NOT NULL ," + // 6: oldMessageTime
                "\"OLD_MESSAGE\" TEXT," + // 7: oldMessage
                "\"STATUS\" INTEGER NOT NULL ," + // 8: status
                "\"SOURCE_TYPE\" INTEGER NOT NULL ," + // 9: sourceType
                "\"NICK_NAME\" TEXT," + // 10: nickName
                "\"SEND_STATE\" INTEGER NOT NULL ," + // 11: sendState
                "\"USER_AVATAR\" TEXT);"); // 12: userAvatar
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAT_LIST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChatListBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMUid());
        stmt.bindString(3, entity.getPeerUid());
        stmt.bindLong(4, entity.getUserType());
        stmt.bindLong(5, entity.getUnreadMsgCount());
        stmt.bindLong(6, entity.getAccount());
        stmt.bindLong(7, entity.getOldMessageTime());
 
        String oldMessage = entity.getOldMessage();
        if (oldMessage != null) {
            stmt.bindString(8, oldMessage);
        }
        stmt.bindLong(9, entity.getStatus());
        stmt.bindLong(10, entity.getSourceType());
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(11, nickName);
        }
        stmt.bindLong(12, entity.getSendState());
 
        String userAvatar = entity.getUserAvatar();
        if (userAvatar != null) {
            stmt.bindString(13, userAvatar);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChatListBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMUid());
        stmt.bindString(3, entity.getPeerUid());
        stmt.bindLong(4, entity.getUserType());
        stmt.bindLong(5, entity.getUnreadMsgCount());
        stmt.bindLong(6, entity.getAccount());
        stmt.bindLong(7, entity.getOldMessageTime());
 
        String oldMessage = entity.getOldMessage();
        if (oldMessage != null) {
            stmt.bindString(8, oldMessage);
        }
        stmt.bindLong(9, entity.getStatus());
        stmt.bindLong(10, entity.getSourceType());
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(11, nickName);
        }
        stmt.bindLong(12, entity.getSendState());
 
        String userAvatar = entity.getUserAvatar();
        if (userAvatar != null) {
            stmt.bindString(13, userAvatar);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChatListBean readEntity(Cursor cursor, int offset) {
        ChatListBean entity = new ChatListBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // mUid
            cursor.getString(offset + 2), // peerUid
            cursor.getInt(offset + 3), // userType
            cursor.getInt(offset + 4), // unreadMsgCount
            cursor.getLong(offset + 5), // account
            cursor.getLong(offset + 6), // oldMessageTime
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // oldMessage
            cursor.getInt(offset + 8), // status
            cursor.getInt(offset + 9), // sourceType
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // nickName
            cursor.getInt(offset + 11), // sendState
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // userAvatar
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChatListBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMUid(cursor.getString(offset + 1));
        entity.setPeerUid(cursor.getString(offset + 2));
        entity.setUserType(cursor.getInt(offset + 3));
        entity.setUnreadMsgCount(cursor.getInt(offset + 4));
        entity.setAccount(cursor.getLong(offset + 5));
        entity.setOldMessageTime(cursor.getLong(offset + 6));
        entity.setOldMessage(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStatus(cursor.getInt(offset + 8));
        entity.setSourceType(cursor.getInt(offset + 9));
        entity.setNickName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSendState(cursor.getInt(offset + 11));
        entity.setUserAvatar(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChatListBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChatListBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChatListBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
