package com.code.data.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.code.data.sqlbean.MsgBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MSG_BEAN".
*/
public class MsgBeanDao extends AbstractDao<MsgBean, Long> {

    public static final String TABLENAME = "MSG_BEAN";

    /**
     * Properties of entity MsgBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Fp = new Property(1, String.class, "fp", false, "FP");
        public final static Property IsBroadcaster = new Property(2, boolean.class, "isBroadcaster", false, "IS_BROADCASTER");
        public final static Property MsgId = new Property(3, long.class, "msgId", false, "MSG_ID");
        public final static Property Pts = new Property(4, long.class, "pts", false, "PTS");
        public final static Property Account = new Property(5, long.class, "account", false, "ACCOUNT");
        public final static Property UserType = new Property(6, int.class, "userType", false, "USER_TYPE");
        public final static Property Uid = new Property(7, String.class, "uid", false, "UID");
        public final static Property PeerUid = new Property(8, String.class, "peerUid", false, "PEER_UID");
        public final static Property SourceType = new Property(9, int.class, "sourceType", false, "SOURCE_TYPE");
        public final static Property Content = new Property(10, String.class, "content", false, "CONTENT");
        public final static Property LocalPath = new Property(11, String.class, "localPath", false, "LOCAL_PATH");
        public final static Property Status = new Property(12, int.class, "status", false, "STATUS");
        public final static Property State = new Property(13, int.class, "state", false, "STATE");
        public final static Property Progress = new Property(14, double.class, "progress", false, "PROGRESS");
        public final static Property ActualTime = new Property(15, long.class, "actualTime", false, "ACTUAL_TIME");
        public final static Property NickName = new Property(16, String.class, "nickName", false, "NICK_NAME");
        public final static Property Avatar = new Property(17, String.class, "avatar", false, "AVATAR");
        public final static Property Wight = new Property(18, int.class, "wight", false, "WIGHT");
        public final static Property Height = new Property(19, int.class, "height", false, "HEIGHT");
        public final static Property Size = new Property(20, int.class, "size", false, "SIZE");
        public final static Property Time = new Property(21, int.class, "time", false, "TIME");
        public final static Property Ext = new Property(22, String.class, "ext", false, "EXT");
        public final static Property Hash = new Property(23, String.class, "hash", false, "HASH");
    }


    public MsgBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MsgBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MSG_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FP\" TEXT," + // 1: fp
                "\"IS_BROADCASTER\" INTEGER NOT NULL ," + // 2: isBroadcaster
                "\"MSG_ID\" INTEGER NOT NULL ," + // 3: msgId
                "\"PTS\" INTEGER NOT NULL ," + // 4: pts
                "\"ACCOUNT\" INTEGER NOT NULL ," + // 5: account
                "\"USER_TYPE\" INTEGER NOT NULL ," + // 6: userType
                "\"UID\" TEXT NOT NULL ," + // 7: uid
                "\"PEER_UID\" TEXT NOT NULL ," + // 8: peerUid
                "\"SOURCE_TYPE\" INTEGER NOT NULL ," + // 9: sourceType
                "\"CONTENT\" TEXT," + // 10: content
                "\"LOCAL_PATH\" TEXT," + // 11: localPath
                "\"STATUS\" INTEGER NOT NULL ," + // 12: status
                "\"STATE\" INTEGER NOT NULL ," + // 13: state
                "\"PROGRESS\" REAL NOT NULL ," + // 14: progress
                "\"ACTUAL_TIME\" INTEGER NOT NULL ," + // 15: actualTime
                "\"NICK_NAME\" TEXT," + // 16: nickName
                "\"AVATAR\" TEXT," + // 17: avatar
                "\"WIGHT\" INTEGER NOT NULL ," + // 18: wight
                "\"HEIGHT\" INTEGER NOT NULL ," + // 19: height
                "\"SIZE\" INTEGER NOT NULL ," + // 20: size
                "\"TIME\" INTEGER NOT NULL ," + // 21: time
                "\"EXT\" TEXT," + // 22: ext
                "\"HASH\" TEXT);"); // 23: hash
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MSG_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MsgBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fp = entity.getFp();
        if (fp != null) {
            stmt.bindString(2, fp);
        }
        stmt.bindLong(3, entity.getIsBroadcaster() ? 1L: 0L);
        stmt.bindLong(4, entity.getMsgId());
        stmt.bindLong(5, entity.getPts());
        stmt.bindLong(6, entity.getAccount());
        stmt.bindLong(7, entity.getUserType());
        stmt.bindString(8, entity.getUid());
        stmt.bindString(9, entity.getPeerUid());
        stmt.bindLong(10, entity.getSourceType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(11, content);
        }
 
        String localPath = entity.getLocalPath();
        if (localPath != null) {
            stmt.bindString(12, localPath);
        }
        stmt.bindLong(13, entity.getStatus());
        stmt.bindLong(14, entity.getState());
        stmt.bindDouble(15, entity.getProgress());
        stmt.bindLong(16, entity.getActualTime());
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(17, nickName);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(18, avatar);
        }
        stmt.bindLong(19, entity.getWight());
        stmt.bindLong(20, entity.getHeight());
        stmt.bindLong(21, entity.getSize());
        stmt.bindLong(22, entity.getTime());
 
        String ext = entity.getExt();
        if (ext != null) {
            stmt.bindString(23, ext);
        }
 
        String hash = entity.getHash();
        if (hash != null) {
            stmt.bindString(24, hash);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MsgBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fp = entity.getFp();
        if (fp != null) {
            stmt.bindString(2, fp);
        }
        stmt.bindLong(3, entity.getIsBroadcaster() ? 1L: 0L);
        stmt.bindLong(4, entity.getMsgId());
        stmt.bindLong(5, entity.getPts());
        stmt.bindLong(6, entity.getAccount());
        stmt.bindLong(7, entity.getUserType());
        stmt.bindString(8, entity.getUid());
        stmt.bindString(9, entity.getPeerUid());
        stmt.bindLong(10, entity.getSourceType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(11, content);
        }
 
        String localPath = entity.getLocalPath();
        if (localPath != null) {
            stmt.bindString(12, localPath);
        }
        stmt.bindLong(13, entity.getStatus());
        stmt.bindLong(14, entity.getState());
        stmt.bindDouble(15, entity.getProgress());
        stmt.bindLong(16, entity.getActualTime());
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(17, nickName);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(18, avatar);
        }
        stmt.bindLong(19, entity.getWight());
        stmt.bindLong(20, entity.getHeight());
        stmt.bindLong(21, entity.getSize());
        stmt.bindLong(22, entity.getTime());
 
        String ext = entity.getExt();
        if (ext != null) {
            stmt.bindString(23, ext);
        }
 
        String hash = entity.getHash();
        if (hash != null) {
            stmt.bindString(24, hash);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MsgBean readEntity(Cursor cursor, int offset) {
        MsgBean entity = new MsgBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // fp
            cursor.getShort(offset + 2) != 0, // isBroadcaster
            cursor.getLong(offset + 3), // msgId
            cursor.getLong(offset + 4), // pts
            cursor.getLong(offset + 5), // account
            cursor.getInt(offset + 6), // userType
            cursor.getString(offset + 7), // uid
            cursor.getString(offset + 8), // peerUid
            cursor.getInt(offset + 9), // sourceType
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // content
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // localPath
            cursor.getInt(offset + 12), // status
            cursor.getInt(offset + 13), // state
            cursor.getDouble(offset + 14), // progress
            cursor.getLong(offset + 15), // actualTime
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // nickName
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // avatar
            cursor.getInt(offset + 18), // wight
            cursor.getInt(offset + 19), // height
            cursor.getInt(offset + 20), // size
            cursor.getInt(offset + 21), // time
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // ext
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23) // hash
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MsgBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFp(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsBroadcaster(cursor.getShort(offset + 2) != 0);
        entity.setMsgId(cursor.getLong(offset + 3));
        entity.setPts(cursor.getLong(offset + 4));
        entity.setAccount(cursor.getLong(offset + 5));
        entity.setUserType(cursor.getInt(offset + 6));
        entity.setUid(cursor.getString(offset + 7));
        entity.setPeerUid(cursor.getString(offset + 8));
        entity.setSourceType(cursor.getInt(offset + 9));
        entity.setContent(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setLocalPath(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setStatus(cursor.getInt(offset + 12));
        entity.setState(cursor.getInt(offset + 13));
        entity.setProgress(cursor.getDouble(offset + 14));
        entity.setActualTime(cursor.getLong(offset + 15));
        entity.setNickName(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setAvatar(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setWight(cursor.getInt(offset + 18));
        entity.setHeight(cursor.getInt(offset + 19));
        entity.setSize(cursor.getInt(offset + 20));
        entity.setTime(cursor.getInt(offset + 21));
        entity.setExt(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setHash(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MsgBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MsgBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MsgBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
